import Head from 'next/head'
import Image from 'next/image'
import Avatar from '../components/Avatar'
import {SearchIcon,MicrophoneIcon ,ViewGridIcon} from '@heroicons/react/solid'
import Fotter from '../components/Fotter'
import { useRef } from 'react'
import {useRouter} from 'next/router'
export default function Home() {

  const router = useRouter();

  const inputRef =useRef(null);

  const SearchHandler=(e)=>{
   e.preventDefault();
    const Term = inputRef.current.value;
    if(!Term) return;

    router.push(`/search?query=${Term}&start=${0}`);
  }

  return (
    <div className="relative h-screen">
      <Head>
        <title>Faysal - Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <header className="flex items-center justify-between p-5 text-sm text-gray-700">
          <div className="flex items-center space-x-4">
            <p className="link">Home</p>
            <p className="link">About</p>
          </div>

          <div className="flex items-center space-x-4">
            <p className="link">Gmail</p>
            <p className="link">Images</p>
          
          

            <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />
           <Avatar src="IMG_20200304_214448.JPG" />
          </div>
        </header>

        <form className="mt-40 flex flex-col items-center flex-grow">
          <Image src="/logo.png" className="google__img" width={300} height={100} />

          <div className="flex items-center w-full mt-5 max-w-md  hover:shadow-lg focus-within:shadow-lg rounded-full border border-gray-200 px-5 py-3 sm:max-w-xl md:max-w-xl lg:max-w-2xl">
            <SearchIcon className="h-5 text-gray-400 mr-3"/>
            <input type="text" placeholder="Search in here..." className="flex-grow focus:outline-none" ref={inputRef} />
            <MicrophoneIcon className="h-5"/>
          </div>

          <div className="mt-9  flex flex-col w-1/2 space-y-3 sm:space-x-3 sm:space-y-0 sm:flex-row items-center justify-center">
            <button className="btn" onClick={SearchHandler} type="submit">Google Search</button>
            <button className="btn" onClick={SearchHandler} type="submit">I'm Felling Lucky</button>
          </div>
        </form>

        <Fotter />
    </div>
  )
}
